### ISSUE TITLE
options is not defined

### ISSUE THREAD

**Issue by bmichotte** [okaufmann/laravel-elixir-typescript#14]
Hi there, using the latest version

```
Message:
    options is not defined
Stack:
ReferenceError: options is not defined
    at TypescriptTask.typescript (..../node_modules/elixir-typescript/dist/TypescriptTask.js:85:35)
    at TypescriptTask.gulpTask (..../node_modules/elixir-typescript/dist/TypescriptTask.js:66:88)
    at TypescriptTask.run (..../node_modules/laravel-elixir/dist/tasks/Task.js:138:31)
    at Gulp.<anonymous> (..../node_modules/laravel-elixir/dist/tasks/GulpBuilder.js:65:67)
    at module.exports (..../node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (..../node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (..../node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (..../node_modules/orchestrator/index.js:134:8)
    at runNextSet (..../node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (..../node_modules/run-sequence/index.js:75:5)
```

https://github.com/okaufmann/laravel-elixir-typescript/blob/master/src/TypescriptTask.js#L57

```
--- return gulpTypescript(options, gulpTypescript.reporter.defaultReporter());
+++ return gulpTypescript(this.options, gulpTypescript.reporter.defaultReporter());
```

**Comment by okaufmann** [comment]
I rewritet the while Task to es6 and did not test it without a tsconfig.json file. Use latest verson 3.0.2 where I fixed it.
